{
 "title": "DevOps Lab Service — Monitoring",
 "tags": [
  "devops",
  "prometheus",
  "fastapi",
  "grafana"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "stat",
   "description": "Количество HTTP-запросов в секунду",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Requests by status code",
   "type": "timeseries",
   "description": "HTTP-запросы по статус-кодам",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_requests_total[1m]))",
     "legendFormat": "HTTP {{status_code}}"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "description": "95-й перцентиль задержки HTTP-запросов",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "Average latency by endpoint",
   "type": "timeseries",
   "description": "Средняя задержка по endpoint'ам",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_request_duration_seconds_sum[5m])) / sum by (endpoint) (rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}